// tailwind.config.js
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#000000",
        surface: "#000000",
        "surface-dim": "#000000",
        "surface-bright": "#1a1a1a",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#0a0a0a",
        "surface-container": "#121212",
        "surface-container-high": "#1a1a1a",
        "surface-container-highest": "#242424",
        "on-background": "#ffffff",
        "on-surface": "#ffffff",
        "on-surface-variant": "#cccccc",
        primary: "#a855f7",
        "on-primary": "#ffffff",
        "primary-container": "#9333ea",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#d8b4fe",
        secondary: "#d8b4fe",
        "on-secondary": "#ffffff",
        "secondary-container": "#3b0764",
        "on-secondary-container": "#f3e8ff",
        tertiary: "#c084fc",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#7e22ce",
        "on-tertiary-container": "#fae8ff",
        outline: "#666666",
        "outline-variant": "#333333",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#ffdbcc",
        "on-primary-fixed": "#07006c",
        "secondary-fixed": "#d3e4fe",
        "primary-fixed": "#e1e0ff",
        "surface-tint": "#a855f7",
        "on-tertiary-fixed-variant": "#7b2f00",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-surface": "#cccccc",
        "on-secondary-fixed": "#0b1c30",
        "inverse-on-surface": "#000000",
        "on-tertiary-fixed": "#351000",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary-fixed-dim": "#ffb695",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#2f2ebe"
      },
    },
  },
  plugins: [],
}