// tailwind.config.js
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#131b2e",
        "background": "#0b1326",
        "tertiary-fixed": "#ffdbcc",
        "on-primary-fixed": "#07006c",
        "on-background": "#dae2fd",
        "secondary-fixed": "#d3e4fe",
        "primary-fixed": "#e1e0ff",
        "surface-tint": "#c0c1ff",
        "surface-container": "#171f33",
        "surface-dim": "#0b1326",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-surface-variant": "#c7c4d8",
        "surface-container-high": "#222a3d",
        "on-secondary": "#213145",
        "secondary-container": "#3a4a5f",
        "inverse-primary": "#494bd6",
        "surface-container-highest": "#2d3449",
        "secondary-fixed-dim": "#b7c8e1",
        "on-surface": "#dae2fd",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#a44100",
        "tertiary": "#ffb695",
        "surface": "#0b1326",
        "primary-container": "#4b4dd8",
        "on-primary-container": "#d9d8ff",
        "inverse-surface": "#dae2fd",
        "primary": "#c0c1ff",
        "outline": "#918fa1",
        "on-secondary-fixed": "#0b1c30",
        "inverse-on-surface": "#283044",
        "surface-container-lowest": "#060e20",
        "secondary": "#b7c8e1",
        "surface-variant": "#2d3449",
        "on-tertiary-fixed": "#351000",
        "surface-bright": "#31394d",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary-fixed-dim": "#ffb695",
        "on-primary": "#1000a9",
        "primary-fixed-dim": "#c0c1ff",
        "outline-variant": "#464555",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#2f2ebe",
        "error": "#ffb4ab",
        "on-tertiary": "#571f00",
        "on-tertiary-container": "#ffd2be",
        "on-secondary-container": "#a9bad3"
      },
    },
  },
  plugins: [],
}